### ISSUE TITLE
Build failures for 1.114 in a docker build

### ISSUE THREAD

**Issue by scop** [perl5-utils/File-ShareDir#11]
rt.cpan.org does not work for me at the moment (502 proxy errors / timeouts), so filing here instead:

I have a docker build that is currently failing due to failing tests in File-ShareDir 1.114:
https://github.com/scop/bash-completion/blob/docker-tools/Dockerfile

The failures are listed below. Full build log: [build.log](https://github.com/perl5-utils/File-ShareDir/files/2127479/build.log)

```
# Testing File::ShareDir 1.114, Perl 5.024001, /usr/bin/perl, UID: 0
t/01_compile.t ..... ok
t/02_main.t ........ ok
t/03_extensions.t .. ok

#   Failed test 'New module directory without read permission'
#   at t/04_fail.t line 80.
#                   ''
#     doesn't match '(?^:No read permission)'

#   Failed test 'New module directory without read permission'
#   at t/04_fail.t line 94.
#                   ''
#     doesn't match '(?^:but no read permissions)'

#   Failed test 'Unreadable dist_file'
#   at t/04_fail.t line 122.
#                   ''
#     doesn't match '(?^:No read permission)'

#   Failed test 'Unreadable module_file'
#   at t/04_fail.t line 125.
#                   ''
#     doesn't match '(?^:No read permission)'

#   Failed test 'Unreadable class_file'
#   at t/04_fail.t line 130.
#                   ''
#     doesn't match '(?^:cannot be read, no read permissions)'
# Looks like you failed 5 tests of 24.
t/04_fail.t ........ 
Dubious, test returned 5 (wstat 1280, 0x500)
Failed 5/24 subtests 
t/05_class.t ....... ok
t/06_old.t ......... ok

Test Summary Report
-------------------
t/04_fail.t      (Wstat: 1280 Tests: 24 Failed: 5)
  Failed tests:  10-11, 15-17
  Non-zero exit status: 5
Files=6, Tests=71,  0 wallclock secs ( 0.03 usr  0.00 sys +  0.21 cusr  0.05 csys =  0.29 CPU)
Result: FAIL
Failed 1/6 test programs. 5/71 subtests failed.

```

**Comment by rehsack** [comment]
To many negations :(

Anyway - the error is reproducible by running the test as root.
Do you know how to run the Travis tests as root to add a regression test?

Cheers

**Comment by scop** [comment]
I believe using a sudo-enabled container would be one starting point.
https://docs.travis-ci.com/user/reference/trusty/#Using-Trusty

Another way would be to add a test run that's inside a docker container. Want me to have a look into this?

**Comment by scop** [comment]
Took a brief look, and just add one run with `sudo make test` was so non-intrusive that I didn't bother with docker, see #13

**Comment by rehsack** [comment]
Cool, thanks.
When one fine day a docker container test will pass your way, please drop a note.
